HRIS.Web.Mvc4/Models/TreeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Project.Web.Mvc4.Models
{
    public class TreeViewModel
    {
        public TreeViewModel()
        {
            Tags=new List<string>();
        }
        public int Id { get; set; }
        public string Name { get; set; }
        public string ImageName { get; set; }
        public bool HasChildren { get; set; }
        public List<string> Tags { get; set; }
        public IList<TreeViewModel> Items { get; set; }
    }
}

HRIS.Web.Mvc4/Controllers/IndexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web.Mvc;
using Project.Web.Mvc4.Factories;
using Project.Web.Mvc4.Models.GridModel;
using Souccar.Domain.DomainModel;
using Project.Web.Mvc4.Models;
using Souccar.Domain.Extensions;
using Project.Web.Mvc4.Extensions;
using Souccar.Core.Extensions;
using Souccar.Infrastructure.Extenstions;

using Project.Web.Mvc4.Helpers.Resource;
using Project.Web.Mvc4.Models.Navigation;
using Project.Web.Mvc4.ProjectModels;
using Project.Web.Mvc4.ProjectModels;
using Souccar.Core.Fasterflect;
using Souccar.Infrastructure.Core;
using Project.Web.Mvc4.Helpers.DomainExtensions;
using Souccar.Domain.Audit;

namespace Project.Web.Mvc4.Controllers
{
    public class IndexController : Controller
    {
        

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GetGridModel(string name = null)
        {
            var model = GridViewModelFactory.Create(name.ToType(), null);

            model.ToolbarCommands.Clear();
           
            if (model.AuthorizedToAdd)
            {
                model.ToolbarCommands.Add(new ToolbarCommand()
                {
                    Name = BuiltinCommand.Create.ToString().ToLower(),
                    Text = model.Create
                });
            }
            model.ToolbarCommands.Add(new ToolbarCommand()
            {
                Text = model.ClearFiltering,
                ClassName = "k-grid-clear-filters",
                ImageClass = "k-icon k-clear-filter",
                Additional = false
            });

            model.ToolbarCommands.Add(new ToolbarCommand()
            {
                Text = model.ClearSorting,
                ClassName = "k-grid-clear-sorting",
                ImageClass = "k-icon k-delete",
                Additional = false
            });

            model.ActionList = new ActionList();
            foreach (var view in model.Views)
            {
                view.EditorMode = GridEditorMode.Inline.ToString().ToLower();

                view.ReadUrl = "Index/Read";
                view.CreateUrl = "Index/Create";
                view.UpdateUrl = "Index/Update";
                view.DestroyUrl = "Index/Delete";
            }
            return Json(model);
        }
        /// <summary>
        /// Author: Yaseen Alrefaee
        /// </summary>
        /// <returns></returns>
        //public ActionResult IndexesName()
        //{
        //    return Json(Assembly.GetAssembly(typeof(Employee)).GetIndexClasses().Select(x=>new {Value=x.Key.FullName,Text=x.Value}).ToList(),JsonRequestBehavior.AllowGet);
        //}

        /// <summary>
        /// Author: Yaseen Alrefaee
        /// </summary>
        /// <param name="moduleName"></param>
        /// <returns></returns>
        public ActionResult IndexesNameForModule(string moduleName)
        {
            Type chooseType = null;
           var module= BuildNavigation.GetModule(moduleName);
         var agg=   module.Aggregates.FirstOrDefault();


            var objectType = AppDomain.CurrentDomain.GetAssemblies().Where(x => x.GetName().GetPublicKey().Length==0);
            foreach (var assembly in objectType)
            {
                var type = assembly.GetTypes().FirstOrDefault(x => x.IsClass && x.Name == agg.AggregateId);
                if (type != null)
                {
                    chooseType = type;
                    break;
                }

            }


            return Json(Assembly.GetAssembly(chooseType).GetIndexClassesByModule(moduleName).Select(x => new { Value = x.Key.FullName, Text = x.Key.GetLocalized() }).ToList(), JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Author: Yaseen Alrefaee
        /// 
        /// </summary>
        /// <param name="name"></param>
        /// <param name="pageSize"></param>
        /// <param name="skip"></param>
        /// <param name="sort"></param>
        /// <param name="filter"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Read(string name, int pageSize = 10, int skip = 0, IEnumerable<GridSort> sort = null, GridFilter filter = null)
        {
            var type = name.ToType();
            var query = IndexHelper.GetAllIndexItems(type);
            CrudController.UpdateFilter(filter, type);

            var dataSourse = DataSourceResult.GetDataSourceResult(query, name.ToType(), pageSize, skip, true, sort, filter);
            return new Souccar.Web.Mvc.JsonNet.JsonNetResult(new { Data = name.ToType().ToDynamicData(dataSourse.Data), TotalCount = dataSourse.Total });
        }

        /// <summary>
        /// Author: Yaseen Alrefaee
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        //[HttpGet]
        public ActionResult ReadToList(string typeName, RequestInformation requestInformation)
        {
            var type = typeName.ToType();
            
            var data = CrudController.GetAll(type);
            var result = data.ToList().Cast<IndexEntity>().OrderBy(x => x.Order).Select(x => new DropdownItemViewModel { Id = x.Id, Name = x.Name });
            return Json(new { Data = result }, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Author: Yaseen Alrefaee
        /// 
        /// </summary>
        /// <param name="name"></param>
        /// <param name="data"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Update(string name, Dictionary<string, object> data)
        {
            var indexValue = data["Name"].ToString().Trim();
            var index = (IndexEntity)name.ToType().GetById((int)data["Id"]);
            var errors = IndexHelper.GetIndexValidationResult(name, indexValue, (int)data["Id"]);
            if (errors.Any())
                return Json(new { Data = index, Errors = errors });
            try
            {
                var indexEntity = IndexHelper.GeDeletedIndexItemByName(indexValue, name.ToType());
                if (indexEntity != null)
                {
                    index.IsVertualDeleted = true;
                    indexEntity.IsVertualDeleted = false;
                    indexEntity.Order = int.Parse(data["Order"].ToString());
                    ServiceFactory.ORMService.SaveTransaction(new List<IAggregateRoot>() { index, indexEntity }, UserExtensions.CurrentUser, indexEntity, OperationType.Update);
                    return Json(new { Data = index });
                }
                else
                {
                    index.Name = indexValue;
                    index.Order = int.Parse(data["Order"].ToString());
                    ServiceFactory.ORMService.SaveTransaction(new List<IAggregateRoot>() { index }, UserExtensions.CurrentUser, index, OperationType.Update);
                    return Json(new { Data = index });
                }
            }
            catch (Exception e)
            {
                return Json(new { Data = index, Errors = new { Exception = e.Message } });
            }
            return Json(new { Data = index });
        }

        /// <summary>
        /// Author: Yaseen Alrefaee
        /// 
        /// </summary>
        /// <param name="name"></param>
        /// <param name="data"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Delete(string name, Dictionary<string, object> data)
        {
            var index = (IndexEntity)name.ToType().GetById((int)data["Id"]);
            try
            {
                index.IsVertualDeleted=true;
                ServiceFactory.ORMService.SaveTransaction(new List<IAggregateRoot>() { index }, UserExtensions.CurrentUser, index, OperationType.Delete);
            }
            catch (Exception e)
            {
                return Json(new { Data = data, Errors = e.Message });
            }

            return Json(new { Data = data });
        }

        /// <summary>
        /// Author: Yaseen Alrefaee
        /// 
        /// </summary>
        /// <param name="name"></param>
        /// <param name="data"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Destroy(string name, Dictionary<string, object> data)
        {
            var index = (IndexEntity)name.ToType().GetById((int)data["Id"]);
            try
            {
                index.Delete();
            }
            catch (Exception e)
            {
                return Json(new { Data = data, Errors = e.Message });
            }

            return Json(new { Data = data });
        }

        /// <summary>
        /// Author: Yaseen Alrefaee
        /// 
        /// </summary>
        /// <param name="name"></param>
        /// <param name="data"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Create(string name, Dictionary<string, object> data)
        {
            var indexValue = data["Name"].ToString().Trim();
            var newIndex = (IndexEntity)Activator.CreateInstance(name.ToType());
            var errors = IndexHelper.GetIndexValidationResult(name, indexValue, (int)data["Id"]);
            if (errors.Any())
                return Json(new { Data = newIndex, Errors = errors });
            try
            {
                var indexEntity = IndexHelper.GeDeletedIndexItemByName(indexValue, name.ToType());
                if (indexEntity != null)
                {
                    indexEntity.IsVertualDeleted = false;
                    indexEntity.Order = int.Parse(data["Order"].ToString());
                    ServiceFactory.ORMService.SaveTransaction(new List<IAggregateRoot>() { indexEntity }, UserExtensions.CurrentUser, indexEntity, OperationType.Insert);
                    return Json(new { Data = indexEntity });
                }
                else
                {

HRIS.Web.Mvc4/Areas/ReportGenerator/Views/ReportBuilder/AggregateFilterRow.cshtml
@*<%@ Control Language="C#" Inherits="System.Web.Mvc.ViewUserControl<Souccar.ReportGenerator.Domain.QueryBuilder.QueryTree>" %>
<%@ Import Namespace="Souccar.ReportGenerator.Domain.QueryBuilder" %>
<%@ Import Namespace="UI.Extensions" %>
<table>
    <tr>
        <td>
            <div class="editor-label-required">
                <%: Html.Label("Aggregate Fields") %>
            </div>
            <div class="editor-field">
                <%: Html.Telerik().ComboBox()
                    .Name("cmbAggregates")
                    //.BindTo((SelectList)ViewData["AggregateProperties"])
                    .BindTo(Model.Nodes.SelectFromList(x => x.PropertyName, y => y.DisplayName))
                    %>
            </div>
        </td>
        <td>
            <div class="editor-label-required">
                <%: Html.Label("Aggregate Functions") %>
            </div>
            <div class="editor-field">
                <%: Html.Telerik().ComboBox().Name("cmbAggregateFunction")
                .BindTo(QueryTree.GetAvailableAggregateFilters().ToList().SelectFromList(x=>x.Key.ToString(),y=>y.Value))%>
            </div>
        </td>
        <td>
            <div class="editor-label-required">
                <%: Html.Label("Aggregate Operator") %>
            </div>
            <div class="editor-field">
                <%: Html.Telerik().ComboBox().Name("cmbAggregateOperator")
            .BindTo(QueryTree.GetAvailableFilterOperators().ToList().SelectFromList(x=>x.Key.ToString(),y=>y.Value))%>
            </div>
        </td>
        <td>
            <div class="editor-label-required">
                <%: Html.Label("Value") %>
            </div>
            <div class="editor-field">
                <div id="divAggregateFilterValue">
                    <%:Html.Telerik().NumericTextBox().Name("txtAggregateFilterValue")%>
                </div>
            </div>
        </td>
        <td>
            <input type="button" id="RemoveAggregateFilterRow" value="X" onclick="RemoveAggregateFilterRow(this)" />
        </td>
    </tr>
</table>*@

HRIS.Web.Mvc4/Areas/ReportGenerator/Views/ReportBuilder/DisplayReport.cshtml
@using Project.Web.Mvc4
@using Project.Web.Mvc4.Helpers

@{
    Layout = "~/Views/ReportGenerator/ReportGeneratorLayOut.cshtml";
    var dir = "";
    var kdir = "";
    var localdir = "";
    if (CurrentLocale.Language == Locale.Rtl)
    {
        dir = "rtl";
        kdir = "k-rtl";
        localdir = "local-rtl";
    }

}

@Html.DevExpress().DocumentViewer(settings =>
{

    settings.Name = "DocumentViewer";
    settings.CallbackRouteValues = new
    {
        Controller = "ReportBuilder",
        Action = "DocumentViewerPartial"
    };
    settings.ExportRouteValues = new
    {
        Controller = "ReportBuilder",
        Action = "DocumentViewerExport"
    };
    settings.Report = (DevExpress.XtraReports.UI.XtraReport)Model;
}).GetHtml()

<script>
    $(document).ready(function() {
        var dir = '@dir';
        if (dir != "") {
            $(".dxXtraReports_PageTable").attr("dir", @dir);
            $("#report_div").attr("dir", @dir);}
    });


</script>
@*@Html.Action("DocumentViewerPartial","ReportBuilder")*@

HRIS.Web.Mvc4/Areas/ReportGenerator/Views/ReportBuilder/DisplayReports.cshtml
@*@Html.Action("DocumentViewerPartial")*@

HRIS.Web.Mvc4/Areas/ReportGenerator/Views/ReportBuilder/FilterRow.cshtml
@*<%@ Control Language="C#" Inherits="System.Web.Mvc.ViewUserControl<Souccar.ReportGenerator.Domain.QueryBuilder.QueryTree>" %>
<table>
    <tr>
        <td>
            <div class="editor-label-required">
                <%: Html.Label("Field") %>
            </div>
            <div class="editor-field">
                <%: Html.Telerik().ComboBox()
                    .Name("cmbLeafs")
                    .BindTo((SelectList)ViewData["QueryLeafProperties"])
                    .ClientEvents(e => e.OnChange("LeafChanged"))%>
            </div>
        </td>
        <td>
            <div class="editor-label-required">
                <%: Html.Label("Operator") %>
            </div>
            <div class="editor-field">
                <%: Html.Telerik().ComboBox().Name("cmbOperator")%>
            </div>
        </td>
        <td>
            <div class="editor-label-required">
                <%: Html.Label("Value") %>
            </div>
            <div class="editor-field">
                <div id="divFilterValue">
                    <%:Html.TextBox("txtFilterValue") %>
                </div>
            </div>
        </td>
        <td>
            <input type="button" id="RemoveFilterRow" value="X" onclick="RemoveFilterRow(this)" />
        </td>
    </tr>
</table>*@

HRIS.Web.Mvc4/Areas/ReportGenerator/Views/ReportBuilder/Index.cshtml
@*@Scripts.Render("~/bundles/underscore")
@Scripts.Render("~/bundles/modernizr")
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryui")
@Scripts.Render("~/bundles/jqueryval")*@

@Html.Action("Create1")
@*<div id="displaybutton" class="k-button k-button-icontext">
    Display Report
</div>
<script>
   //$("#button").click(function () {
   //     var window = $("#popupBasic");

        @*$.ajax({
            url: "@Url.Action("Create1", "ReportBuilder", new { area = "ReportGenerator" })",
            type: "POST",
            success: function (data) {
                window.html(data);
            }
        });*@

        // var existWindow = window.data("kendoWindow");
        //if (existWindow == null) {
        //    window.kendoWindow({
        //        modal: true,
        //        resizable: true,
        //        width: 900,
        //        height: 600,
        //        title: "View Intormation",
        //        open: function () {
        //            window.data("kendoWindow").center();
        //        }
        //    });
        //}
        //else {
        //    existWindow.open();
        //}
  // });

    @*$("#displaybutton").click(function () {
            var window = $("#displayReportWindow");

            location.href = "ReportBuilder/DocumentViewerPartial";
            alert("hahah");
        });
    //</script>*@

HRIS.Web.Mvc4/Areas/ReportGenerator/Views/ReportBuilder/MasterGrid.cshtml
@*<%@ Control Language="C#" Inherits="System.Web.Mvc.ViewUserControl<dynamic>" %>
<%@ Import Namespace="Souccar.ReportGenerator.Domain.QueryBuilder" %>
<fieldset class="ParentFieldset">
    <legend class="ParentLegend">
        <%: Resources.Areas.ReportGenerator.Domain.Entities.Report.ReportModel.ReportGridTitle %></legend>
    <table width="100%">
        <tr>
            <td>
                <%
                    Html.Telerik().Grid<Report>("reports")
                        .Name("Grid")
                        .DataKeys(k => k.Add(o => o.Id))
                        .DataBinding(dataBinding => dataBinding.Server().Delete("Delete", "QueryBuilder"))
                        .DataBinding(dataBinding => dataBinding.Server().Insert("Insert", "QueryBuilder"))
                        .Scrollable(builder => builder.Height(350))
                        .ToolBar(toolBar => toolBar.Template(() =>
                        { 
                %>
                <table class="GridToolBar">
                    <tr>
                        <td>
                            <% if (ViewData["CanCreate"] != null && (bool)ViewData["CanCreate"])
                               {%>
                            <a href="<%:Url.Action("Insert", "QueryBuilder")%>">
                                <img src="<%= Url.Content("~/Content/Ribbon/Icons/48/112.png") %>" title="<%: Resources.Shared.Buttons.Function.Add %>"
                                    alt="<%: Resources.Shared.Buttons.Function.Add %>" height="36" width="36" align="middle" />
                            </a>
                            <% } %>
                        </td>
                    </tr>
                </table>
                <% 
                        }))
                        .Filterable()
                        .Sortable(s => s.OrderBy(order => order.Add(o => o.Id).Descending()))
                        .Columns(c =>
                                     {
                                         c.Bound(b => b.Id).Width(35).Title(Resources.Shared.Model.Fields.Id).Groupable(false).Filterable(false).Sortable(false);
                                         c.Bound(o => o.Name).Sortable(true).Title(Resources.Areas.ReportGenerator.Domain.Entities.Report.ReportModel.Name);
                                         c.Bound(o => o.Template.Name).Sortable(true).Title(Resources.Areas.ReportGenerator.Domain.Entities.Report.ReportModel.ReportTemplate);
                                         c.Bound(o => o.Id).Title("")
                                                .Format(Html.ActionLink(Resources.Shared.Buttons.Function.ViewReport, "Index", "DynamicReport", new { reportId = "{0}", Area = "Reporting" }, new { target = "_blank" }).ToHtmlString())
                                                .Encoded(false)
                                                .Width("5%").Sortable(false).Filterable(false);
                                         c.Command(s =>
                                                       {
                                                           s.Custom("EditCommand").ButtonType(GridButtonType.Image).Ajax(false)
                                                                        .Action("Insert", "QueryBuilder")
                                                                        .HtmlAttributes(new { @class = "t-edit" });
                                                           if (ViewData["CanDelete"] != null &&
                                                               (bool)ViewData["CanDelete"])
                                                           {
                                                               s.Delete().ButtonType(GridButtonType.Image);
                                                           }
                                                       }).Width("8%");

                                     })
                       .Pageable(p => p.PageSize(5))
                       .Render();

                %>
            </td>
        </tr>
    </table>
</fieldset>*@

HRIS.Web.Mvc4/Areas/ReportGenerator/Views/ReportBuilder/ReportResult.cshtml
@{
    ViewBag.Title = "DisplayReports";
}
@Html.DevExpress().DocumentViewer(settings =>
    {
        
        settings.Name = "DocumentViewer";
        settings.CallbackRouteValues = new
        {
            Controller = "ReportBuilder",
            Action = "DocumentViewerPartial"
        };
        settings.ExportRouteValues = new
        {
            Controller = "ReportBuilder",
            Action = "DocumentViewerExport"
        };
        settings.Report = (DevExpress.XtraReports.UI.XtraReport)Model;
    }).GetHtml()
@*@Scripts.Render("~/bundles/mainTheme")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")*@

HRIS.Web.Mvc4/Areas/ReportGenerator/Views/ReportBuilder/Test.cshtml
@using Project.Web.Mvc4
@{
    ViewBag.Title = "Test";
    Layout = "~/Views/ReportGenerator/ReportGeneratorLayOut.cshtml";
}


@{
    var dir = "";
    var kdir = "";
    var localdir = "";
    if (CurrentLocale.Language == Locale.Rtl)
    {
        dir = "rtl";
        kdir = "k-rtl";
        localdir = "local-rtl";
    }

}

@Html.DevExpress().DocumentViewer(settings =>
{

    settings.Name = "DocumentViewer";
    settings.CallbackRouteValues = new
    {
        Controller = "ReportBuilder",
        Action = "DocumentViewerPartial"
    };
    settings.ExportRouteValues = new
    {
        Controller = "ReportBuilder",
        Action = "DocumentViewerExport"
    };
    settings.Report = (DevExpress.XtraReports.UI.XtraReport)Model;
}).GetHtml()

<script>
    $(document).ready(function() {
        if (dir != "") {
            $(".dxXtraReports_PageTable").attr("dir", @dir);
            $("#report_div").attr("dir", @dir);}
    });


</script>

HRIS.Web.Mvc4/Areas/ReportGenerator/Views/ReportBuilder/Tree.cshtml
@*<%@ Control Language="C#" Inherits="System.Web.Mvc.ViewUserControl<System.Collections.Generic.IEnumerable<Souccar.ReportGenerator.Domain.QueryBuilder.QueryTree>>" %>
Aggregate Tree:
<%: Html.Telerik().TreeView()
                .ClientEvents(e => e.OnSelect("TreeNodeSelected"))
                .ClientEvents(e => e.OnLoad("TreeLoaded"))
                .ClientEvents(e => e.OnNodeDrop("onNodeDrop"))
                .DragAndDrop(true)
            .Name("TreeView")
            .ExpandAll(true)
                .BindTo(Model, map => map.For<Souccar.ReportGenerator.Domain.QueryBuilder.QueryTree>(bin => bin
		    .ItemDataBound((item, node) => 
            { 
                item.Text = node.DisplayName; 
                item.Value = node.FullClassPath;
                item.Selected = node.FullClassPath==(string)TempData["lastTreeNodeSelectedValue"];
            })
            .Children(node2 => node2.Nodes.OrderBy(o => o.SelectOrder))))%>
<script type="text/javascript">
    function TreeLoaded(e) {
        var lastSelectedNode = '<%:TempData["lastTreeNodeSelectedValue"]%>';
        if (lastSelectedNode != "") {
            var treeview = $('#TreeView').data('tTreeView');
            var selectedNode = treeview.findByValue(lastSelectedNode);
            e.item = selectedNode;
            TreeNodeSelected(e);
        }
    }

    function IsDragAndDropValid(e) {
        var treeview = $('#TreeView').data('tTreeView');
        var parentSourceNode = treeview.getItemText($(e.item).parent().closest(".t-item"));
        var parentDestinationNode = treeview.getItemText($(e.destinationItem).parent().closest(".t-item"));
        if (parentSourceNode != parentDestinationNode || e.dropPosition == "over") {
            return false;
        }
        return true;
    }

    function onNodeDrop(e) {
        if (IsDragAndDropValid(e) == false) {
            e.preventDefault();
        }
        else {
            var treeview = $('#TreeView').data('tTreeView');
            var dropPosition = e.dropPosition;
            var destinationNodeId = treeview.getItemValue(e.destinationItem);
            var sourceNodeId = treeview.getItemValue(e.item);
            var parentNodeId = treeview.getItemValue($(e.item).parent().closest(".t-item"));

            $.ajax({
                url: '<%:Url.Action("ReorderNodes", "QueryBuilder", new { area = "Reporting"})%>/',
                type: "POST",
                async: false,
                traditional: true,
                data: {
                    sourceNodeId: sourceNodeId,
                    destinationNodeId: destinationNodeId,
                    parentNodeId: parentNodeId,
                    dropPosition: dropPosition
                },
                success: function (result) {
                    if (result.Success == false) {
                        alert('Error While Reorder Please Try Again!');
                    }
                }
            });
        }
    }
</script>*@